from PyQt5 import QtCore, QtGui, QtWidgets

#from denklem import AddEquation
from Lib.myInterface.equation import AddEquation
import os


class myDesign(object):

    def yeniac(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = AddEquation()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, thisDesign):
        thisDesign.setObjectName("thisDesign")
        thisDesign.resize(1077, 890)
        thisDesign.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        thisDesign.setWindowIcon(icon)
        thisDesign.setToolTip("")
        thisDesign.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(thisDesign)
        self.centralwidget.setObjectName("centralwidget")

        self.pso_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.pso_gb.setGeometry(QtCore.QRect(10, 10, 931, 261))
        self.pso_gb.setObjectName("pso_gb")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.pso_gb)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 140, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.pso_verticalLayout_lbl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.pso_verticalLayout_lbl.setContentsMargins(0, 0, 0, 0)
        self.pso_verticalLayout_lbl.setObjectName("pso_verticalLayout_lbl")
        self.pso_lbl_ps = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_ps.setFont(font)
        self.pso_lbl_ps.setObjectName("pso_lbl_ps")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_ps)
        self.pso_lbl_mi = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_mi.setFont(font)
        self.pso_lbl_mi.setObjectName("pso_lbl_mi")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_mi)
        self.pso_lbl_keu = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_keu.setFont(font)
        self.pso_lbl_keu.setObjectName("pso_lbl_keu")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_keu)
        self.pso_lbl_c1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_c1.setFont(font)
        self.pso_lbl_c1.setObjectName("pso_lbl_c1")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_c1)
        self.pso_lbl_c2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_c2.setFont(font)
        self.pso_lbl_c2.setObjectName("pso_lbl_c2")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_c2)
        self.pso_lbl_cas = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_cas.setFont(font)
        self.pso_lbl_cas.setObjectName("pso_lbl_cas")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_cas)
        self.pso_lbl_cus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_cus.setFont(font)
        self.pso_lbl_cus.setObjectName("pso_lbl_cus")
        self.pso_verticalLayout_lbl.addWidget(self.pso_lbl_cus)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.pso_gb)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 20, 211, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.pso_verticalLayout_le = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.pso_verticalLayout_le.setContentsMargins(0, 0, 0, 0)
        self.pso_verticalLayout_le.setObjectName("pso_verticalLayout_le")
        self.pso_le_ps = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_ps.setObjectName("pso_le_ps")
        self.pso_verticalLayout_le.addWidget(self.pso_le_ps)
        self.pso_le_mi = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_mi.setObjectName("pso_le_mi")
        self.pso_verticalLayout_le.addWidget(self.pso_le_mi)
        self.pso_le_keu = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_keu.setObjectName("pso_le_keu")
        self.pso_verticalLayout_le.addWidget(self.pso_le_keu)
        self.pso_le_c1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_c1.setObjectName("pso_le_c1")
        self.pso_verticalLayout_le.addWidget(self.pso_le_c1)
        self.pso_le_c2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_c2.setObjectName("pso_le_c2")
        self.pso_verticalLayout_le.addWidget(self.pso_le_c2)
        self.pso_le_cas = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_cas.setObjectName("pso_le_cas")
        self.pso_verticalLayout_le.addWidget(self.pso_le_cas)
        self.pso_le_cus = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pso_le_cus.setObjectName("pso_le_cus")
        self.pso_verticalLayout_le.addWidget(self.pso_le_cus)

        self.pso_btn_psoic = QtWidgets.QPushButton(self.pso_gb)
        self.pso_btn_psoic.setGeometry(QtCore.QRect(670, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pso_btn_psoic.setFont(font)
        self.pso_btn_psoic.setObjectName("pso_btn_psoic")
        self.pso_btn_psoic.clicked.connect(self.d_oku_pso)

        self.pso_btn_dok = QtWidgets.QPushButton(self.pso_gb)
        self.pso_btn_dok.setGeometry(QtCore.QRect(390, 60, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pso_btn_dok.setFont(font)
        self.pso_btn_dok.setObjectName("pso_btn_dok")
        self.pso_btn_do = QtWidgets.QPushButton(self.pso_gb)
        self.pso_btn_do.setGeometry(QtCore.QRect(390, 130, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pso_btn_do.setFont(font)
        self.pso_btn_do.setObjectName("pso_btn_do")
        self.pso_lbl_eicx = QtWidgets.QLabel(self.pso_gb)
        self.pso_lbl_eicx.setGeometry(QtCore.QRect(570, 50, 90, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_eicx.setFont(font)
        self.pso_lbl_eicx.setObjectName("pso_lbl_eicx")
        self.pso_lbl_is = QtWidgets.QLabel(self.pso_gb)
        self.pso_lbl_is.setGeometry(QtCore.QRect(570, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_is.setFont(font)
        self.pso_lbl_is.setObjectName("pso_lbl_is")
        self.pso_le_eicx = QtWidgets.QLineEdit(self.pso_gb)
        self.pso_le_eicx.setGeometry(QtCore.QRect(670, 60, 119, 20))
        self.pso_le_eicx.setObjectName("pso_le_eicx")
        self.pso_le_is = QtWidgets.QLineEdit(self.pso_gb)
        self.pso_le_is.setGeometry(QtCore.QRect(670, 90, 119, 20))
        self.pso_le_is.setObjectName("pso_le_is")
        self.pso_le_uyg = QtWidgets.QLineEdit(self.pso_gb)
        self.pso_le_uyg.setGeometry(QtCore.QRect(800, 60, 119, 20))
        self.pso_le_uyg.setObjectName("pso_le_uyg")
        self.pso_lbl_uyg = QtWidgets.QLabel(self.pso_gb)
        self.pso_lbl_uyg.setGeometry(QtCore.QRect(800, 30, 119, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pso_lbl_uyg.setFont(font)
        self.pso_lbl_uyg.setObjectName("pso_lbl_uyg")

        self.lbl_pso_denklem = QtWidgets.QLabel(self.pso_gb)
        self.lbl_pso_denklem.setGeometry(QtCore.QRect(390, 220, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_pso_denklem.setFont(font)
        self.lbl_pso_denklem.setText("")
        self.lbl_pso_denklem.setObjectName("lbl_pso_denklem")

        self.pso_btn_dg = QtWidgets.QPushButton(self.centralwidget)
        self.pso_btn_dg.setGeometry(QtCore.QRect(950, 20, 111, 251))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pso_btn_dg.clicked.connect(self.yeniac)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pso_btn_dg.setFont(font)
        self.pso_btn_dg.setObjectName("pso_btn_dg")

        self.ga_btn_dg = QtWidgets.QPushButton(self.centralwidget)
        self.ga_btn_dg.setGeometry(QtCore.QRect(950, 300, 111, 251))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ga_btn_dg.setFont(font)
        self.ga_btn_dg.setObjectName("ga_btn_dg")
        self.ga_btn_dg.clicked.connect(self.yeniac)

        self.ga_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.ga_gb.setGeometry(QtCore.QRect(10, 290, 931, 261))
        self.ga_gb.setWhatsThis("")
        self.ga_gb.setObjectName("ga_gb")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.ga_gb)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 140, 231))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.ga_verticalLayout_lbl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.ga_verticalLayout_lbl.setContentsMargins(0, 0, 0, 0)
        self.ga_verticalLayout_lbl.setObjectName("ga_verticalLayout_lbl")
        self.ga_lbl_ks = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_ks.setFont(font)
        self.ga_lbl_ks.setObjectName("ga_lbl_ks")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_ks)
        self.ga_lbl_gs = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_gs.setFont(font)
        self.ga_lbl_gs.setObjectName("ga_lbl_gs")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_gs)
        self.ga_lbl_mi = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_mi.setFont(font)
        self.ga_lbl_mi.setObjectName("ga_lbl_mi")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_mi)
        self.ga_lbl_keu = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_keu.setFont(font)
        self.ga_lbl_keu.setObjectName("ga_lbl_keu")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_keu)
        self.ga_lbl_co = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_co.setFont(font)
        self.ga_lbl_co.setObjectName("ga_lbl_co")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_co)
        self.ga_lbl_mo = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_mo.setFont(font)
        self.ga_lbl_mo.setObjectName("ga_lbl_mo")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_mo)
        self.ga_lbl_cas = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_cas.setFont(font)
        self.ga_lbl_cas.setObjectName("ga_lbl_cas")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_cas)
        self.ga_lbl_cus = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_cus.setFont(font)
        self.ga_lbl_cus.setObjectName("ga_lbl_cus")
        self.ga_verticalLayout_lbl.addWidget(self.ga_lbl_cus)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.ga_gb)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(160, 20, 211, 241))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.ga_verticalLayout_le = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.ga_verticalLayout_le.setContentsMargins(0, 0, 0, 0)
        self.ga_verticalLayout_le.setObjectName("ga_verticalLayout_le")
        self.ga_le_ks = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_ks.setObjectName("ga_le_ks")
        self.ga_verticalLayout_le.addWidget(self.ga_le_ks)
        self.ga_le_gs = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_gs.setObjectName("ga_le_gs")
        self.ga_verticalLayout_le.addWidget(self.ga_le_gs)
        self.ga_le_mi = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_mi.setObjectName("ga_le_mi")
        self.ga_verticalLayout_le.addWidget(self.ga_le_mi)
        self.ga_le_keu = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_keu.setObjectName("ga_le_keu")
        self.ga_verticalLayout_le.addWidget(self.ga_le_keu)
        self.ga_le_co = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_co.setObjectName("ga_le_co")
        self.ga_verticalLayout_le.addWidget(self.ga_le_co)
        self.ga_le_mo = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_mo.setObjectName("ga_le_mo")
        self.ga_verticalLayout_le.addWidget(self.ga_le_mo)
        self.ga_le_cas = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_cas.setObjectName("ga_le_cas")
        self.ga_verticalLayout_le.addWidget(self.ga_le_cas)
        self.ga_le_cus = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.ga_le_cus.setObjectName("ga_le_cus")
        self.ga_verticalLayout_le.addWidget(self.ga_le_cus)

        self.ga_btn_gaic = QtWidgets.QPushButton(self.ga_gb)
        self.ga_btn_gaic.setGeometry(QtCore.QRect(670, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ga_btn_gaic.setFont(font)
        self.ga_btn_gaic.setObjectName("ga_btn_gaic")
        self.ga_btn_gaic.clicked.connect(self.d_oku_ga)

        self.ga_btn_dok = QtWidgets.QPushButton(self.ga_gb)
        self.ga_btn_dok.setGeometry(QtCore.QRect(390, 60, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ga_btn_dok.setFont(font)
        self.ga_btn_dok.setObjectName("ga_btn_dok")
        self.ga_btn_do = QtWidgets.QPushButton(self.ga_gb)
        self.ga_btn_do.setGeometry(QtCore.QRect(390, 130, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ga_btn_do.setFont(font)
        self.ga_btn_do.setObjectName("ga_btn_do")
        self.label_29 = QtWidgets.QLabel(self.ga_gb)
        self.label_29.setGeometry(QtCore.QRect(570, 90, 116, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_28 = QtWidgets.QLabel(self.ga_gb)
        self.label_28.setGeometry(QtCore.QRect(570, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.ga_le_eicx = QtWidgets.QLineEdit(self.ga_gb)
        self.ga_le_eicx.setGeometry(QtCore.QRect(670, 50, 119, 20))
        self.ga_le_eicx.setObjectName("ga_le_eicx")
        self.ga_le_is = QtWidgets.QLineEdit(self.ga_gb)
        self.ga_le_is.setGeometry(QtCore.QRect(670, 90, 119, 20))
        self.ga_le_is.setObjectName("ga_le_is")
        self.ga_le_uyg = QtWidgets.QLineEdit(self.ga_gb)
        self.ga_le_uyg.setGeometry(QtCore.QRect(800, 50, 119, 20))
        self.ga_le_uyg.setObjectName("ga_le_uyg")

        self.ga_lbl_uyg = QtWidgets.QLabel(self.ga_gb)
        self.ga_lbl_uyg.setGeometry(QtCore.QRect(800, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ga_lbl_uyg.setFont(font)
        self.ga_lbl_uyg.setObjectName("ga_lbl_uyg")

        self.lbl_ga_denklem = QtWidgets.QLabel(self.ga_gb)
        self.lbl_ga_denklem.setGeometry(QtCore.QRect(390, 220, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ga_denklem.setFont(font)
        self.lbl_ga_denklem.setText("")
        self.lbl_ga_denklem.setObjectName("lbl_ga_denklem")

        self.verticalLayoutWidget_12.raise_()
        self.verticalLayoutWidget_13.raise_()
        self.ga_btn_gaic.raise_()
        self.verticalLayoutWidget.raise_()
        self.ga_btn_dok.raise_()
        self.ga_btn_do.raise_()
        self.label_29.raise_()
        self.label_28.raise_()
        self.ga_le_eicx.raise_()
        self.ga_le_is.raise_()
        self.ga_le_uyg.raise_()
        self.ga_lbl_uyg.raise_()

        self.abc_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.abc_gb.setGeometry(QtCore.QRect(10, 560, 931, 261))
        self.abc_gb.setWhatsThis("")
        self.abc_gb.setObjectName("abc_gb")
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.abc_gb)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 20, 140, 231))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.abc_verticalLayout_lbl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.abc_verticalLayout_lbl.setContentsMargins(0, 0, 0, 0)
        self.abc_verticalLayout_lbl.setObjectName("abc_verticalLayout_lbl")
        self.abc_lbl_yks = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_yks.setFont(font)
        self.abc_lbl_yks.setObjectName("abc_lbl_yks")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_yks)
        self.abc_lbl_mi = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_mi.setFont(font)
        self.abc_lbl_mi.setObjectName("abc_lbl_mi")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_mi)
        self.abc_lbl_keu = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_keu.setFont(font)
        self.abc_lbl_keu.setObjectName("abc_lbl_keu")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_keu)
        self.abc_lbl_kbl = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_kbl.setFont(font)
        self.abc_lbl_kbl.setObjectName("abc_lbl_kbl")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_kbl)
        self.abc_lbl_cas = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_cas.setFont(font)
        self.abc_lbl_cas.setObjectName("abc_lbl_cas")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_cas)
        self.abc_lbl_cus = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_cus.setFont(font)
        self.abc_lbl_cus.setObjectName("abc_lbl_cus")
        self.abc_verticalLayout_lbl.addWidget(self.abc_lbl_cus)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.abc_gb)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(160, 20, 211, 241))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.abc_verticalLayout_le = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.abc_verticalLayout_le.setContentsMargins(0, 0, 0, 0)
        self.abc_verticalLayout_le.setObjectName("abc_verticalLayout_le")
        self.abc_le_yks = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_yks.setObjectName("abc_le_yks")
        self.abc_verticalLayout_le.addWidget(self.abc_le_yks)
        self.abc_le_mi = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_mi.setObjectName("abc_le_mi")
        self.abc_verticalLayout_le.addWidget(self.abc_le_mi)
        self.abc_le_keu = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_keu.setObjectName("abc_le_keu")
        self.abc_verticalLayout_le.addWidget(self.abc_le_keu)
        self.abc_le_kbi = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_kbi.setObjectName("abc_le_kbi")
        self.abc_verticalLayout_le.addWidget(self.abc_le_kbi)
        self.abc_le_cas = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_cas.setObjectName("abc_le_cas")
        self.abc_verticalLayout_le.addWidget(self.abc_le_cas)
        self.abc_le_cus = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.abc_le_cus.setObjectName("abc_le_cus")
        self.abc_verticalLayout_le.addWidget(self.abc_le_cus)
        self.abc_btn_abcic = QtWidgets.QPushButton(self.abc_gb)
        self.abc_btn_abcic.setGeometry(QtCore.QRect(670, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.abc_btn_abcic.setFont(font)
        self.abc_btn_abcic.setObjectName("abc_btn_abcic")
        self.abc_btn_abcic.clicked.connect(self.d_oku_abc)


        self.abc_btn_dok = QtWidgets.QPushButton(self.abc_gb)
        self.abc_btn_dok.setGeometry(QtCore.QRect(390, 60, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.abc_btn_dok.setFont(font)
        self.abc_btn_dok.setObjectName("abc_btn_dok")
        self.abc_btn_do = QtWidgets.QPushButton(self.abc_gb)
        self.abc_btn_do.setGeometry(QtCore.QRect(390, 130, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.abc_btn_do.setFont(font)
        self.abc_btn_do.setObjectName("abc_btn_do")
        self.abc_lbl_is = QtWidgets.QLabel(self.abc_gb)
        self.abc_lbl_is.setGeometry(QtCore.QRect(570, 80, 90, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_is.setFont(font)
        self.abc_lbl_is.setObjectName("abc_lbl_is")
        self.abc_lbl_eicx = QtWidgets.QLabel(self.abc_gb)
        self.abc_lbl_eicx.setGeometry(QtCore.QRect(570, 50, 90, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_eicx.setFont(font)
        self.abc_lbl_eicx.setObjectName("abc_lbl_eicx")
        self.abc_le_is = QtWidgets.QLineEdit(self.abc_gb)
        self.abc_le_is.setGeometry(QtCore.QRect(670, 90, 119, 20))
        self.abc_le_is.setObjectName("abc_le_is")
        self.abc_le_eicx = QtWidgets.QLineEdit(self.abc_gb)
        self.abc_le_eicx.setGeometry(QtCore.QRect(670, 50, 119, 20))
        self.abc_le_eicx.setObjectName("abc_le_eicx")
        self.abc_le_uyg = QtWidgets.QLineEdit(self.abc_gb)
        self.abc_le_uyg.setGeometry(QtCore.QRect(800, 50, 119, 20))
        self.abc_le_uyg.setObjectName("abc_le_uyg")
        self.abc_lbl_uyg = QtWidgets.QLabel(self.abc_gb)
        self.abc_lbl_uyg.setGeometry(QtCore.QRect(800, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.abc_lbl_uyg.setFont(font)
        self.abc_lbl_uyg.setObjectName("abc_lbl_uyg")

        self.lbl_abc_denklem = QtWidgets.QLabel(self.abc_gb)
        self.lbl_abc_denklem.setGeometry(QtCore.QRect(390, 210, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_abc_denklem.setFont(font)
        self.lbl_abc_denklem.setText("")
        self.lbl_abc_denklem.setObjectName("lbl_abc_denklem")

        self.abc_btn_dg = QtWidgets.QPushButton(self.centralwidget)
        self.abc_btn_dg.setGeometry(QtCore.QRect(950, 570, 111, 251))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.abc_btn_dg.setFont(font)
        self.abc_btn_dg.setObjectName("abc_btn_dg")
        self.abc_btn_dg.clicked.connect(self.yeniac)

        self.btn_cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis.setGeometry(QtCore.QRect(470, 840, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cikis.setFont(font)
        self.btn_cikis.setObjectName("btn_cikis")
        self.btn_cikis.clicked.connect(thisDesign.close)

        thisDesign.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(thisDesign)
        self.statusbar.setObjectName("statusbar")
        thisDesign.setStatusBar(self.statusbar)

        self.retranslateUi(thisDesign)

        QtCore.QMetaObject.connectSlotsByName(thisDesign)

    def d_oku_abc(self):
        if os.path.isfile("denklem.txt"):
            with open("denklem.txt", "r") as dosya:
                y = dosya.readline()
                print(y)

        if self.abc_btn_abcic.clicked:
            self.lbl_ga_denklem.setText(" ")
            self.lbl_pso_denklem.setText(" ")
            self.lbl_abc_denklem.setText(y)

    def d_oku_ga(self):
        if os.path.isfile("denklem.txt"):
            with open("denklem.txt", "r") as dosya:
                y = dosya.readline()
                print(y)

        if self.ga_btn_gaic.clicked:
            self.lbl_pso_denklem.setText(" ")
            self.lbl_abc_denklem.setText(" ")
            self.lbl_ga_denklem.setText(y)

    def d_oku_pso(self):
        if os.path.isfile("denklem.txt"):
            with open("denklem.txt", "r") as dosya:
                y = dosya.readline()
                print(y)

        if self.ga_btn_gaic.clicked:
            self.lbl_ga_denklem.setText(" ")
            self.lbl_abc_denklem.setText(" ")
            self.lbl_pso_denklem.setText(y)

    def retranslateUi(self, thisDesign):
        _translate = QtCore.QCoreApplication.translate
        thisDesign.setWindowTitle(_translate("thisDesign", "Sezgisel Algoritmalar"))
        self.pso_gb.setTitle(
            _translate("thisDesign", "PARTICAL SWARM OPTIMIZATION - Parçacık Sürü Optimizasyonu"))
        self.pso_lbl_ps.setText(_translate("thisDesign", "Parçacık Sayısı"))
        self.pso_lbl_mi.setText(_translate("thisDesign", "Maksimum İterasyon"))
        self.pso_lbl_keu.setText(_translate("thisDesign", "Kabul Edilebilir Uygunluk"))
        self.pso_lbl_c1.setText(_translate("thisDesign", "C1 Sabiti"))
        self.pso_lbl_c2.setText(_translate("thisDesign", "C2 Sabiti"))
        self.pso_lbl_cas.setText(_translate("thisDesign", "Çözüm için Alt Sınır"))
        self.pso_lbl_cus.setText(_translate("thisDesign", "Çözüm için Üst Sınır"))
        self.pso_btn_psoic.setText(_translate("thisDesign", "PSO ile ÇÖZ"))
        self.pso_btn_dok.setText(_translate("thisDesign", "default olarak KAYDET"))
        self.pso_btn_do.setText(_translate("thisDesign", "default OKU"))
        self.pso_lbl_eicx.setText(_translate("thisDesign", "En iyi çözüm X"))
        self.pso_lbl_is.setText(_translate("thisDesign", "İterasyon Sayısı"))
        self.pso_lbl_uyg.setText(_translate("thisDesign", "Uygunluklar"))
        self.pso_btn_dg.setText(_translate("thisDesign", "Denklem Gir"))
        self.ga_btn_dg.setText(_translate("thisDesign", "Denklem Gir"))
        self.ga_gb.setTitle(_translate("thisDesign", "GENETIC ALGORITHM - Genetik Algoritma"))
        self.ga_lbl_ks.setText(_translate("thisDesign", "Kromozom Sayısı"))
        self.ga_lbl_gs.setText(_translate("thisDesign", "Gen Sayısı"))
        self.ga_lbl_mi.setText(_translate("thisDesign", "Maksimum İterasyon"))
        self.ga_lbl_keu.setText(_translate("thisDesign", "Kabul Edilebilir Uygunluk"))
        self.ga_lbl_co.setText(_translate("thisDesign", "Çaprazlama Oranı"))
        self.ga_lbl_mo.setText(_translate("thisDesign", "Mutasyon Oranı"))
        self.ga_lbl_cas.setText(_translate("thisDesign", "Çözüm için Alt Sınır"))
        self.ga_lbl_cus.setText(_translate("thisDesign", "Çözüm için Üst Sınır"))
        self.ga_btn_gaic.setText(_translate("thisDesign", "GA ile ÇÖZ"))
        self.ga_btn_dok.setText(_translate("thisDesign", "default olarak KAYDET"))
        self.ga_btn_do.setText(_translate("thisDesign", "default OKU"))
        self.label_29.setText(_translate("thisDesign", "İterasyon Sayısı"))
        self.label_28.setText(_translate("thisDesign", "En iyi çözüm X"))
        self.ga_lbl_uyg.setText(_translate("thisDesign", "Uygunluklar"))
        self.abc_gb.setTitle(_translate("thisDesign", "ARTIFICAL BEE COLONY - Yapay Arı Kolonisi"))
        self.abc_lbl_yks.setText(_translate("thisDesign", "Yiyecek Kaynağı Sayısı"))
        self.abc_lbl_mi.setText(_translate("thisDesign", "Maksimum İterasyon"))
        self.abc_lbl_keu.setText(_translate("thisDesign", "Kabul Edilebilir Uygunluk"))
        self.abc_lbl_kbl.setText(_translate("thisDesign", "kaynak Bırakma Limiti"))
        self.abc_lbl_cas.setText(_translate("thisDesign", "Çözüm için Alt Sınır"))
        self.abc_lbl_cus.setText(_translate("thisDesign", "Çözüm için Üst Sınır"))
        self.abc_btn_abcic.setText(_translate("thisDesign", "ABC ile ÇÖZ"))
        self.abc_btn_dok.setText(_translate("thisDesign", "default olarak KAYDET"))
        self.abc_btn_do.setText(_translate("thisDesign", "default OKU"))
        self.abc_lbl_is.setText(_translate("thisDesign", "İterasyon Sayısı"))
        self.abc_lbl_eicx.setText(_translate("thisDesign", "En iyi çözüm X"))
        self.abc_lbl_uyg.setText(_translate("thisDesign", "Uygunluklar"))
        self.abc_btn_dg.setText(_translate("thisDesign", "Denklem Gir"))
        self.btn_cikis.setText(_translate("thisDesign", "ÇIKIŞ"))

